---
title: "MLR"
output: html_document
---

```{r setup}
library(data.table)
library(tseries)
library(forecast)
library(TSA)
```
```{r}
traffic_dt <- as.data.table(traffic_2)

traffic_dt[, week_num := as.integer(car::recode(weekday,
    "'Monday'='1';'Tuesday'='2';'Wednesday'='3';'Thursday'='4';
    'Friday'='5';'Saturday'='6';'Sunday'='7'"))]

traffic_dt <- traffic_dt[,c("date_time","traffic_volume","date","weekday","year","temp")]
```

```{r}
ggplot(data = traffic_dt, aes(x = date, y = traffic_volume)) +
  geom_line() + 
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold"),
        strip.text = element_text(size = 9, face = "bold")) +
  labs(x = "Date", y = "Traffic Volume")
```
```{r data prep}
traffic_dt <- traffic_dt[, week_num := as.integer(as.factor(traffic_dt[, weekday]))]
```

```{r}
train_data <- traffic_dt[(traffic_dt$year > 2014 & traffic_dt$year < 2018)]

n_date <- unique(train_data[, date])
n_weekdays <- unique(train_data[, weekday])
period <- 24

data_r <- train_data[(date %in% n_date[20:385])]
```

```{r}
ggplot(data_r, aes(date_time, traffic_volume)) +
  geom_line() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(x = "Date", y = "Traffic Volume")
```

```{r}
ggplot(data_r, aes(date_time, temp)) +
  geom_line() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(x = "Date", y = "Temperature (C)")
```



```{r}
ggplot(data_s_time, aes(x = date_time, y = traffic_volume)) +
  geom_line() +
  xlab("Day") + ylab("Traffic Volume") +
  ggtitle("Traffic Volume Hourly")
```
```{r}
# n_ts_1 <- naive(ts_1)
# 
# res <- residuals(n_ts_1)
# 
# autoplot(res) + 
#   xlab("Day") + ylab("") +
#   ggtitle("Residuals from naïve method")
```

```{r}
library(zoo)
library(lattice)


z <- read.zoo(data_s_time,  header = TRUE, tz = "CST")
xyplot(z)

zAgg <- aggregate(z,  by = as.yearmon,  FUN = mean)


plot(zAgg, xaxt = "n")

tt <- time(zAgg)
m <- format(tt, "%m")
axis(side = 1, at = tt, labels = ifelse(m == "01", trunc(tt), m), cex.axis = .7)
```

```{r}
z <- ts(z)

# volume_fit <- tslm(z ~ , data = data_s)
# fcast <- forecast(volume_fit)
# autoplot(fcast) +
#   ggtitle("Forecasts of beer production using regression") +
#   xlab("Year") + ylab("megalitres")
```

```{r}
data_s <- mutate(data_s, month_year = paste(year(date), formatC(month(date), width = 2, flag = "0")))

data_s <- mutate(data_s, year_day = paste(year(date),formatC(month(date), width = 2, flag = "0"), formatC(day(date),width = 2, flag = "0")))

data_s <- mutate(data_s, week = week(date))

data_s <- mutate(data_s, year = year(date))

data_s$year <- as.factor(data_s$year)

data_s_2 <- data_s[,c("date","traffic_volume","month_year","year_day","week","year")]

str(data_s_2)
```
```{r}
vol_month <- aggregate(data_s_2$traffic_volume, by = list(data_s_2$month_year), FUN = function(x) mean(x, na.rm=T))

my_ts <- ts(vol_month$x, frequency=12, start = c(2016, 06), end = c(2017, 06))
plot(my_ts)
```
```{r}
my_df_ts <- data.frame(traffic_volume = my_ts, as.numeric(time(my_ts)))
names(my_df_ts) <- c("traffic_volume", "time")

mymodel <- tslm(traffic_volume~season,my_df_ts)

my_fc <- forecast(mymodel,h=9, level = c(80))
autoplot(my_fc)

my_ts_2 <- ts(vol_month_te$x, frequency=12, start = c(2017, 06), end = c(2018, 03))
plot(my_ts_2)
```
```{r}
# data_te <- train_data[(date %in% n_date[367:600])]
# 
# data_te <- mutate(data_te, month_year = paste(year(date), formatC(month(date), width = 2, flag = "0")))
# 
# data_te <- mutate(data_te, year_day = paste(year(date),formatC(month(date), width = 2, flag = "0"), formatC(day(date),width = 2, flag = "0")))
# 
# data_te <- mutate(data_te, week = week(date))
# 
# data_te <- mutate(data_te, year = year(date))
# 
# data_te$year <- as.factor(data_te$year)
# 
# data_te_2 <- data_te[,c("date","traffic_volume","month_year","year_day","week","year")]
# 
# str(data_s_2)
# 
# vol_month_te <- aggregate(data_te_2$traffic_volume, by = list(data_te_2$month_year), FUN = function(x) mean(x, na.rm=T))
# 
# my_ts_2 <- ts(vol_month_te$x, frequency=12, start = c(2016, 04), end = c(2017, 01))
# # plot(my_ts_2)
# # lines(fitted(my_fc),col="blue")
# vol_month_te$fitted <- fitted(my_fc)
# 
# ggplot(data_te_2, aes(x = date, y = traffic_volume)) +
#   geom_line(col='red') +
#   geom_line(aes(y=fitted),col='blue')
```

```{r}
vol_day <- aggregate(data_s_2$traffic_volume, by = list(data_s_2$week), FUN = function(x) mean(x, na.rm=T))

my_ts_3 <- ts(vol_day$x, frequency=12, start = c(2015, 06), end = c(2017, 06))
plot(my_ts_3)

my_df_ts_2 <- data.frame(traffic_volume = my_ts_3, as.numeric(time(my_ts_3)))
names(my_df_ts_2) <- c("traffic_volume", "time")

mymodel_2 <- tslm(traffic_volume~season,my_df_ts_2)

my_fc_2 <- forecast(mymodel_2,h=9, level = c(80))
autoplot(my_fc)

my_ts_4 <- ts(vol_day$x, frequency=12, start = c(2016, 06), end = c(2018, 03))
plot(my_ts_4)
```

```{r}
ggplot(data = data.table(Fitted_values = mymodel$fitted.values,
                         Residuals = mymodel$residuals),
       aes(Fitted_values, Residuals)) +
  geom_point(size = 1.7) +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red", size = 1) +
  labs(title = "Fitted values vs Residuals")
```
```{r}
n_date <- unique(data_s[, c("date")])
n_weekdays <- unique(data_s[, c("weekday")])
period <- 24
```

```{r}
data_t <- train_data[(date %in% n_date[57:70])]

ggplot(data_t, aes(date_time, traffic_volume)) +
  geom_line() +
  theme(panel.border = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(x = "Date", y = "Traffic_Volume")
```

```{r}
N <- nrow(data_t)
window <- N / period # number of days in the train set
# 1, ..., period, 1, ..., period - and so on for the daily season 
# using feature "week_num" for the weekly season
matrix_train <- data.table(traffic_volume = data_t[, traffic_volume],
                           Daily = as.factor(rep(1:period, window)),
                           Weekly = as.factor(data_t[, week_num]))
```
```{r}
lm_m_1 <- lm(traffic_volume ~ 0 + ., data = matrix_train)

smmr_1 <- summary(lm_m_1)
paste("R-squared: ",
      round(smmr_1$r.squared, 3),
      ", p-value of F test: ",
      1-pf(smmr_1$fstatistic[1], smmr_1$fstatistic[2], smmr_1$fstatistic[3]))

summary(lm_m_1)
```
```{r}
datas <- rbindlist(list(data_t[, .(traffic_volume, date_time)],
                        data.table(traffic_volume = lm_m_1$fitted.values, data_time = data_t[, date_time])))
datas[, type := rep(c("Real", "Fitted"), each = nrow(data_t))]
 
ggplot(data = datas, aes(date_time, traffic_volume, group = type, colour = type)) +
  geom_line(size = 0.8) +
  theme_bw() +
  labs(x = "Time", y = "Traffic Volume",
       title = "Fit from MLR")
```
```{r}
ggplot(data = data.table(Fitted_values = lm_m_1$fitted.values,
                         Residuals = lm_m_1$residuals,
                         date = datas$date_time),
       aes(date, Residuals)) +
  geom_point(size = 1.7) +
  geom_smooth() +
  geom_hline(yintercept = 0, color = "red", size = 1) +
  labs(title = "residuals")
```
```{r}
ggQQ <- function(lm){
  # extract standardized residuals from the fit
  d <- data.frame(std.resid = rstandard(lm))
  # calculate 1Q/4Q line
  y <- quantile(d$std.resid[!is.na(d$std.resid)], c(0.25, 0.75))
  x <- qnorm(c(0.25, 0.75))
  slope <- diff(y)/diff(x)
  int <- y[1L] - slope * x[1L]
  
  p <- ggplot(data = d, aes(sample = std.resid)) +
    stat_qq(shape = 1, size = 3) +         # open circles
    labs(title = "Normal Q-Q",             # plot title
         x = "Theoretical Quantiles",      # x-axis label
         y = "Standardized Residuals") +   # y-axis label
    geom_abline(slope = slope, intercept = int, linetype = "dashed",
                size = 1, col = "firebrick1") # dashed reference line
  return(p)
}
```

```{r}
ggQQ(lm_m_1)
```
```{r}
lm_m_2 <- lm(traffic_volume ~ 0 + Daily + Weekly + Daily:Weekly,
             data = matrix_train)

summary(lm_m_2)
```

```{r}
datas <- rbindlist(list(data_t[, .(traffic_volume, date_time)],
                        data.table(traffic_volume = lm_m_2$fitted.values, data_time = data_t[, date_time])))
datas[, type := rep(c("Real", "Fitted"), each = nrow(data_t))]
 
ggplot(data = datas, aes(date_time, traffic_volume, group = type, colour = type)) +
  geom_line(size = 0.8) +
  theme_bw() +
  labs(x = "Time", y = "Traffic Volume",
       title = "Fit from MLR")
```

```{r}
ggQQ(lm_m_2)
```
```{r}
predWeekReg <- function(data, set_of_date){
  
  # Subsetting the dataset by dates
  data_train <- data[date %in% set_of_date]
  
  N <- nrow(data_train)
  window <- N / period # number of days in the train set
  # 1, ..., period, 1, ..., period - and so on for the daily season 
  # Using feature "week_num" for the weekly season
  matrix_train <- data.table(Load = data_train[, traffic_volume],
                           Daily = as.factor(rep(1:period, window)),
                           Weekly = as.factor(data_train[, week_num]))
  
  # Creation of the model
  lm_m <- lm(Load ~ 0 + Daily + Weekly + Daily:Weekly, data = matrix_train)
  
  # Creation of the forecast for one week ahead
  pred_week <- predict(lm_m, matrix_train[1:(7*period), -1, with = FALSE])
  
  return(as.vector(pred_week))
}
```

```{r}
mape <- function(real, pred){
  return(100 * mean(abs((real - pred)/real)))
}
```
