---
title: "TS"
output: html_document
---

```{r}
require(data.table)
require(TSA)
require(forecast)
require(xts)
require(tseries)
require(graphics)
```
```{r}
traffic_2 <- mutate(traffic_2, month_year = paste(year(date), formatC(month(date), width = 2, flag = "0")))

month_vol <- aggregate(traffic_2$traffic_volume, by = list(traffic_2$month_year), FUN = function(x) mean(x, na.rm=T))

month_vol <- month_vol %>% rename(traffic_volume = x,
                    month_year = Group.1)
month_vol <- month_vol %>% mutate(month_year = parse_date_time(month_year, "ym"))

month_vol <- month_vol %>% mutate(month = month(month_year),
                                  year = year(month_year))
str(month_vol)

seasonal <- ggplot(month_vol, aes(x = month, y = traffic_volume, group = year)) +
	geom_line(aes(color = year)) +
	theme_classic() +
  ggtitle("Monthly Aggregate Mean Traffic Volume by Year")

seasonal+scale_color_gradientn(colours = rainbow(7))
```
```{r}
day_vol <- aggregate(traffic_2$traffic_volume, by = list(traffic_2$date), FUN = function(x) mean(x, na.rm=T))

day_vol <- day_vol %>% rename(traffic_volume = x,
                  date = Group.1)

day_vol <- day_vol %>% mutate(month = month(date),
                  day = format(as.Date(day_vol$date,format="%Y-%m-%d"), format = "%d"),
                  year = year(date))
str(day_vol)


day_vol_select <- day_vol %>% filter(year == 2016)

monthly <- ggplot(day_vol_select, aes(x = day, y = traffic_volume, group = month)) +
	geom_line(aes(color = month)) +
	theme_classic() +
  ggtitle("Daily Aggregate Mean Traffic Volume by Month in 2013")

monthly
```
```{r}
weekday_vol <- aggregate(traffic_2$traffic_volume, by = list(traffic_2$hour), FUN = function(x) mean(x, na.rm=T))
```

```{r}
# Transform to `ts` class
monthly_traffic_ts <- ts(month_vol$traffic_volume, start = 2012, end = 2018, freq = 12)  # Specify start and end year, measurement frequency (monthly = 12)

# Decompose using `stl()`
monthly_traffic_stl <- stl(monthly_traffic_ts, s.window = "period")

# Generate plots
plot(monthly_traffic_stl)  # top=original data, second=estimated seasonal, third=estimated smooth trend, bottom=estimated irregular element i.e. unaccounted for variation
monthplot(monthly_traffic_ts, choice = "seasonal")  # variation in milk production for each month
seasonplot(monthly_traffic_ts)
```
```{r}
monthly_traffic_model <- window(x = monthly_traffic_ts, start = c(2012), end = c(2016))
monthly_traffic_test <- window(x = monthly_traffic_ts, start = c(2016))

```

```{r}
# Creating model objects of each type of ets model
traffic_ets_auto <- ets(monthly_traffic_model)
traffic_ets_mmm <- ets(monthly_traffic_model, model = "MMM")
traffic_ets_zzz<- ets(monthly_traffic_model, model = "ZZZ")
traffic_ets_mmm_damped <- ets(monthly_traffic_model, model = "MMM", damped = TRUE)

# Creating forecast objects from the model objects
traffic_ets_fc <- forecast(traffic_ets_auto, h = 24)  # `h = 60` means that the forecast will be 60 time periods long, in our case a time period is one month
traffic_ets_mmm_fc <- forecast(traffic_ets_mmm, h = 24)
traffic_ets_zzz_fc <- forecast(traffic_ets_zzz, h = 24)
traffic_ets_mmm_damped_fc <- forecast(traffic_ets_mmm_damped, h = 24)

# Convert forecasts to data frames
traffic_ets_fc_df <- cbind("Month" = rownames(as.data.frame(traffic_ets_fc)), as.data.frame(traffic_ets_fc))  # Creating a data frame
names(traffic_ets_fc_df) <- gsub(" ", "_", names(traffic_ets_fc_df))  # Removing whitespace from column names
traffic_ets_fc_df$Date <- as.Date(paste("01-", traffic_ets_fc_df$Month, sep = ""), format = "%d-%b %Y")  # prepending day of month to date
traffic_ets_fc_df$Model <- rep("ets")  # Adding column of model type

traffic_ets_mmm_fc_df <- cbind("Month" = rownames(as.data.frame(traffic_ets_mmm_fc)), as.data.frame(traffic_ets_mmm_fc))
names(traffic_ets_mmm_fc_df) <- gsub(" ", "_", names(traffic_ets_mmm_fc_df))
traffic_ets_mmm_fc_df$Date <- as.Date(paste("01-", traffic_ets_mmm_fc_df$Month, sep = ""), format = "%d-%b %Y")
traffic_ets_mmm_fc_df$Model <- rep("ets_mmm")

traffic_ets_zzz_fc_df <- cbind("Month" = rownames(as.data.frame(traffic_ets_zzz_fc)), as.data.frame(traffic_ets_zzz_fc))
names(traffic_ets_zzz_fc_df) <- gsub(" ", "_", names(traffic_ets_zzz_fc_df))
traffic_ets_zzz_fc_df$Date <- as.Date(paste("01-", traffic_ets_zzz_fc_df$Month, sep = ""), format = "%d-%b %Y")
traffic_ets_zzz_fc_df$Model <- rep("ets_zzz")

traffic_ets_mmm_damped_fc_df <- cbind("Month" = rownames(as.data.frame(traffic_ets_mmm_damped_fc)), as.data.frame(traffic_ets_mmm_damped_fc))
names(traffic_ets_mmm_damped_fc_df) <- gsub(" ", "_", names(traffic_ets_mmm_damped_fc_df))
traffic_ets_mmm_damped_fc_df$Date <- as.Date(paste("01-", traffic_ets_mmm_damped_fc_df$Month, sep = ""), format = "%d-%b %Y")
traffic_ets_mmm_damped_fc_df$Model <- rep("ets_mmm_damped")

# Combining into one data frame
forecast_all <- rbind(traffic_ets_fc_df, traffic_ets_mmm_fc_df, traffic_ets_zzz_fc_df, traffic_ets_mmm_damped_fc_df)
```

```{r}
accuracy(traffic_ets_fc, monthly_traffic_test)
accuracy(traffic_ets_mmm_fc, monthly_traffic_test)
accuracy(traffic_ets_zzz_fc, monthly_traffic_test)
accuracy(traffic_ets_mmm_damped_fc, monthly_traffic_test)


month_vol$month_date <- as.Date(month_vol$month_year, format = "%Y-%m-%d")

forecast_plot <- ggplot() +
	geom_line(data = month_vol, aes(x = month_date, y = traffic_volume)) +  # Plotting original data
	geom_line(data = forecast_all, aes(x = Date, y = Point_Forecast, colour = Model)) +  # Plotting model forecasts
	theme_classic() +
  ggtitle("Comparison of forecasts to actual")

forecast_plot
```
```{r}
Box.test(diff(monthly_traffic_ts), lag=10, type="Ljung-Box")

ggAcf(month_vol[,"traffic_volume"])

fit <- auto.arima(month_vol[,c("traffic_volume")], seasonal=FALSE)

fit

fit %>% forecast(h=10) %>% autoplot(include=80)
```
```{r}
#datatatata
volume_dt <- traffic_2[,c("date","traffic_volume","date_time")]

volume_dt <- as.data.table(volume_dt)

volume_dt[, week := weekdays(date_time)]

volume_dt[, ':='(week = weekdays(date_time), date = as.Date(date_time))]

unique(volume_dt[, week])

volume_dt <- volume_dt[-c(1:126), ]

n_weekdays <- unique(volume_dt[, week])

n_date <- unique(volume_dt[, date])

period <- 24

str(volume_dt)
```
```{r}
y_ts <- 



```

```{r}
stlARIMAPred <- function(Y, period = 24){
  ts_Y <- ts(Y, start = 0, freq = period)
  dekom <- stl(ts_Y, s.window = "periodic", robust = TRUE)
  arima <- forecast(dekom, h = period, method = "arima")
  return(as.vector(arima$mean))
}

stlEXPPred <- function(Y, period = 24){
  ts_Y <- ts(Y, start = 0, freq = period)
  dekom <- stl(ts_Y, s.window = "periodic", robust = TRUE)
  expo <- forecast(dekom, h = period, method = "ets", etsmodel = "ZZN")
  return(as.vector(expo$mean))
}

mape <- function(real, pred){
  return(100 * mean(abs((real - pred)/real)))
}

predictWeek <- function(data, set_of_date, FUN, train_win = 6){
 
 for_mon <- FUN(data[(week == n_weekdays[1] & date %in% set_of_date), traffic_volume])
 seq_tuethu <- data[(week %in% n_weekdays[2:4] & date %in% set_of_date), traffic_volume]
 for_tuethu <- as.vector(sapply(2:0, function(j)
   FUN(seq_tuethu[(length(seq_tuethu)-(period*j)+1-(train_win*period)):(length(seq_tuethu)-(period*j))])))
 for_fri <- FUN(data[(week == n_weekdays[5] & date %in% set_of_date), traffic_volume])
 for_sat <- FUN(data[(week == n_weekdays[6] & date %in% set_of_date), traffic_volume])
 for_sun <- FUN(data[(week == n_weekdays[7] & date %in% set_of_date), traffic_volume])
 
 return(c(for_mon, for_tuethu, for_fri, for_sat, for_sun))
}
```

```{r}
for_week_arima <- predictWeek(volume_dt, n_date[56:84], stlARIMAPred) # forecast for one week
for_week_exp <- predictWeek(volume_dt, n_date[56:84], stlEXPPred)
real_week <- volume_dt[date %in% n_date[85:91], traffic_volume] # real consumption
c(ARIMA = mape(real_week, for_week_arima),
  EXP = mape(real_week, for_week_exp))
```

```{r}
str(train_data)

ts_tr <- train_data[,c("date_time","traffic_volume")]

x <- ts(ts_tr)

ndiffs(z)

y <- ts(z[1:168])

y.te <- z[169:336]

fit0 <- auto.arima(y)
(bestfit <- list(aicc=fit0$aicc, i=0, j=0, fit=fit0))

fc0 <- forecast(fit0, h=168)
plot(fc0)
```
```{r}
for(i in 1:3) {
  for (j in 1:3){
    z1 <- fourier(ts(y, frequency=7), K=i)
    z2 <- fourier(ts(y, frequency=12), K=j)
    fit <- auto.arima(y, xreg=cbind(z1, z2), seasonal= TRUE)
    if(fit$aicc < bestfit$aicc) {
      bestfit <- list(aicc=fit$aicc, i=i, j=j, fit=fit)
    }
  }
}
bestfit
```
```{r}
fc <- forecast(bestfit$fit, 
               xreg=cbind(
                 fourier(ts(y, frequency=7), K=bestfit$i, h=60),
                 fourier(ts(y, frequency=365), K=bestfit$j, h=60)))
plot(fc)

fc <- forecast(bestfit$fit, 
               xreg=cbind(
                 fourier(ts(y, frequency=30), K=bestfit$i, h=60)))
plot(fc)

```
```{r}
fc.tbats <- forecast(tbats(y, seasonal.periods=c(30, 23)), h=60)
plot(fc.tbats)
```
```{r}
accuracy(fc0, y.te)
accuracy(fc, y.te)
accuracy(fc.tbats, y.te)
```
```{r}
smape <- function(act, fc){
  pred <- as.vector(fc$mean)
  sm <- abs(act - pred) / (abs(act) + abs(pred) + 1e-12)
  200 * mean(sm, na.rm=T)
}
smape(y.te, fc0)
smape(y.te, fc)
smape(y.te, fc.tbats)
```
```{r}
par(mfrow=c(4,1))
plot(as.ts(x))
plot(fc0)
plot(fc)
plot(fc.tbats)
```
```{r arima time series????}
traffic_dt[, date_time := ymd_hms(traffic_dt[["date"]])]
traffic_dt[, date := as.Date(traffic_dt[["date"]], "%Y-%m-%d")]
traffic_dt[, ':='(timestamp = NULL, estimated = NULL, anomaly = NULL)]
str(traffic_dt)

sd_dt <- traffic[,c("date","traffic_volume","date_time")]
sd_dt$date_time = traffic_dt$date_time
num_date <- sd_dt[, .N, .(date)]
num_date

table(num_date[, N])

sd_dt <- sd_dt[!date %in% num_date[c(1,367), date]]

ggplot(sd_dt[, .(traffic_volume, date)], aes(date, traffic_volume)) +
  geom_line() +
  theme(panel.border = element_blank(), panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"), 
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold"),
        strip.text = element_text(size = 12, face = "bold")) +
  labs(x = "Date", y = "Traffic Volume")
```
```{r}
DT_agg <- as.data.table(aggregate(sd_dt[, .(traffic_volume)], by = sd_dt[, .(date_time)],
                                  FUN = sum, simplify = TRUE))
ggplot(DT_agg, aes(date_time, traffic_volume)) +
  geom_line() +
  theme(panel.border = element_blank(), panel.background = element_blank(),
        panel.grid.minor = element_line(colour = "grey90"),
        panel.grid.major = element_line(colour = "grey90"),
        panel.grid.major.x = element_line(colour = "grey90"),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(x = "Date", y = "Traffic Volume")
```
```{r}
Med_Mad <- DT_agg[, .(Med = median(traffic_volume), Mad = mad(traffic_volume)),
                  by = (seq(nrow(DT_agg)) - 1) %% 24]
ggplot(Med_Mad, aes(x = seq, Med)) + 
  geom_line(size = 0.9) +
  geom_ribbon(data = Med_Mad, aes(ymin = Med - Mad, ymax = Med + Mad),
              fill = "firebrick2", alpha = 0.3) +
  theme(title = element_text(size = 14),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(title = "Median daily profile +- deviation (MAD)") +
  labs(x = "Time", y = "Traffic Volume")
```

```{r}
Med_Mad_Week <- DT_agg[, .(Med = median(traffic_volume), Mad = mad(traffic_volume)),
                       by = (seq(nrow(DT_agg)) - 1) %% (24*7)]
ggplot(Med_Mad_Week, aes(x = seq, Med)) + 
  geom_line(size = 0.9) + 
  geom_ribbon(data = Med_Mad_Week, aes(ymin = Med - Mad, ymax = Med + Mad),
              fill = "firebrick2", alpha = 0.3) +
  geom_vline(xintercept = c(47, 47+(48*3), 47+(48*4), 47+(48*5)), linetype = 2, size = 1) +
  theme(title = element_text(size = 14),
        axis.text = element_text(size = 10),
        axis.title = element_text(size = 12, face = "bold")) +
  labs(title = "Median weekly profile +- deviation (MAD)") +
  labs(x = "Time", y = "Traffic Volume")
```

```{r}
sd_dt[, week := weekdays(date_time)]
DT_agg[, ':='(week = weekdays(date), date = as.Date(date))]
unique(DT_agg[, week])
```
```{r}
n_weekdays <- unique(DT_agg[, week])
n_date <- unique(DT_agg[, date])
period <- 24
```

```{r}

ggplot(decomp_stl, aes(x = Date, y = Load)) +
  geom_line() + 
  facet_grid(Type ~ ., scales = "free_y", switch = "y") +
  labs(x = "Date", y = NULL,
       title = "Time Series Decomposition by STL")
```



